# Generated by Django 5.2.14 on 2026-05-30 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_code', models.CharField(max_length=50, unique=True)),
                ('unit_type', models.CharField(choices=[('container', 'Container'), ('individual', 'Individual')], max_length=20)),
                ('container_type', models.CharField(blank=True, choices=[('tray', 'Tray'), ('pot', 'Pot'), ('nursery_bag', 'Nursery Bag'), ('seedling_tray', 'Seedling Tray'), ('other', 'Other')], max_length=20)),
                ('crop_name', models.CharField(max_length=200)),
                ('accession_code', models.CharField(blank=True, max_length=100)),
                ('batch_code', models.CharField(blank=True, max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('location_text', models.CharField(blank=True, max_length=255)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('is_active', models.BooleanField(default=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archive_reason', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tracking_units', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
