# Generated by Django 5.2.14 on 2026-07-29 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_bench_screenhouse_site_accession_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovementHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location_text', models.CharField(blank=True, max_length=255)),
                ('to_location_text', models.CharField(blank=True, max_length=255)),
                ('reason', models.TextField(blank=True)),
                ('moved_at', models.DateTimeField(auto_now_add=True)),
                ('from_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_from', to='inventory.position')),
                ('moved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_movements', to=settings.AUTH_USER_MODEL)),
                ('to_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_to', to='inventory.position')),
                ('tracking_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.trackingunit')),
            ],
            options={
                'ordering': ['-moved_at'],
            },
        ),
    ]
