# Generated by Django 5.2.14 on 2026-05-30 03:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_type', models.CharField(choices=[('routine', 'Routine'), ('issue', 'Issue'), ('follow_up', 'Follow Up'), ('correction', 'Correction'), ('final', 'Final')], default='routine', max_length=20)),
                ('observed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('watch', 'Watch'), ('sick', 'Sick'), ('critical', 'Critical'), ('dead', 'Dead'), ('recovered', 'Recovered')], max_length=20)),
                ('growth_stage', models.CharField(blank=True, max_length=100)),
                ('affected_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('affected_zone', models.CharField(blank=True, max_length=100)),
                ('water_condition', models.CharField(blank=True, max_length=100)),
                ('pest_signs', models.CharField(blank=True, max_length=255)),
                ('disease_signs', models.CharField(blank=True, max_length=255)),
                ('action_taken', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('corrects_observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections', to='monitoring.observation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_observations', to=settings.AUTH_USER_MODEL)),
                ('tracking_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='inventory.trackingunit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ObservationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='observation_photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'heic', 'heif'])])),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='observation_thumbnails/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='monitoring.observation')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='QuantityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('initial', 'Initial'), ('death', 'Death / Culling'), ('recount', 'Recount'), ('correction', 'Correction'), ('loss', 'Loss')], max_length=20)),
                ('quantity_before', models.PositiveIntegerField()),
                ('quantity_change', models.IntegerField()),
                ('quantity_after', models.PositiveIntegerField()),
                ('reason', models.TextField(blank=True)),
                ('event_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quantity_events', to=settings.AUTH_USER_MODEL)),
                ('tracking_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity_events', to='inventory.trackingunit')),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
    ]
