# Generated by Django 5.2.14 on 2026-05-30 07:16

import django.core.validators
import monitoring.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observationphoto',
            name='image',
            field=models.ImageField(upload_to='observation_photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'heic', 'heif']), monitoring.models.validate_observation_image_size, monitoring.models.validate_observation_image_content]),
        ),
    ]
