# Generated by Django 5.2.14 on 2026-05-30 22:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_bench_screenhouse_site_accession_and_more'),
        ('monitoring', '0002_alter_observationphoto_image_validators'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_type', models.CharField(choices=[('watered', 'Watered'), ('fertilised', 'Fertilised'), ('foliar_spray', 'Foliar Spray'), ('fungicide', 'Fungicide'), ('insecticide', 'Insecticide'), ('repotted', 'Repotted'), ('pruned', 'Pruned'), ('isolated', 'Isolated'), ('moved_to_shade', 'Moved to Shade'), ('moved_to_hardening_area', 'Moved to Hardening Area'), ('destroyed', 'Destroyed'), ('other', 'Other')], max_length=30)),
                ('treatment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('product_used', models.CharField(blank=True, max_length=255)),
                ('dose_rate', models.CharField(blank=True, max_length=100)),
                ('reason', models.TextField()),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('pending', 'Pending'), ('improved', 'Improved'), ('no_change', 'No Change'), ('worsened', 'Worsened'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_treatments', to=settings.AUTH_USER_MODEL)),
                ('related_observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatments', to='monitoring.observation')),
                ('tracking_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='inventory.trackingunit')),
            ],
            options={
                'ordering': ['-treatment_date'],
            },
        ),
    ]
