# Generated by Django 5.2.14 on 2026-07-29 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_movementhistory'),
        ('monitoring', '0004_dailyround_dailyrounditem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('recipient_name', models.CharField(max_length=200)),
                ('recipient_organisation', models.CharField(blank=True, max_length=200)),
                ('purpose', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('distributed_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_distribution_events', to=settings.AUTH_USER_MODEL)),
                ('tracking_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_events', to='inventory.trackingunit')),
            ],
            options={
                'ordering': ['-distributed_at'],
            },
        ),
    ]
