# Generated by Django 5.2.14 on 2026-07-30 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_movementhistory'),
        ('monitoring', '0005_distributionevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropagationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('cutting', 'Cutting'), ('seed', 'Seed'), ('tissue_culture', 'Tissue Culture'), ('division', 'Division'), ('grafting', 'Grafting'), ('other', 'Other')], max_length=30)),
                ('quantity_taken', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('propagated_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_propagation_events', to=settings.AUTH_USER_MODEL)),
                ('parent_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propagation_events_as_parent', to='inventory.trackingunit')),
                ('resulting_units', models.ManyToManyField(blank=True, related_name='propagated_from_events', to='inventory.trackingunit')),
            ],
            options={
                'ordering': ['-propagated_at'],
            },
        ),
    ]
